name: Action to build and publish the project as a nuget package to github package registry

on:
  push:
    branches: [main]
      
jobs:
  build:
    runs-on: ubuntu-latest    
    outputs: 
      Version: ${{ steps.gitversion.outputs.SemVer }}
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }} 

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 #fetch-depth is needed for GitVersion
        
    #Install and calculate the new version with GitVersion  
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: 5.x
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion # step id used as reference for output values
    - name: Display GitVersion outputs
      run: |
        echo "Version: ${{ steps.gitversion.outputs.SemVer }}"
        echo "CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}"
    
    #Build/pack the project
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Build and Pack NuGet package
      run: dotnet pack IdentityServer7.csproj -p:Version='${{ steps.gitversion.outputs.SemVer }}' -c Release --output bin/Release
    - name: Configure nuget
      run: dotnet nuget add source --username fegomes --password ${{ secrets.NUGET_PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/braspin/index.json"
    - name: Push package to GitHub packages 
      run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }}  --source "github"
    #Create release
    - name: Create Tag
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_PACKAGE_TOKEN }} 
      with:
        tag_name: ${{ steps.gitversion.outputs.SemVer }}
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.gitversion.outputs.SemVer }}
        name: Release ${{ steps.gitversion.outputs.SemVer }}
        artifacts: "bin/Release/*"
        token: ${{ secrets.NUGET_PACKAGE_TOKEN }}
